### ISSUE TITLE
一个问题

### ISSUE THREAD

**Issue by Meteor2333** [ElluIFX/DP100-PyQt5-GUI#3]
我在打包完成exe后启动应用报了以下错误：
Traceback (most recent call last):
  File "DP100_main.py", line 25, in <module>
  File "DP100_main.py", line 15, in main
  File "DP100_gui.py", line 54, in <module>
AttributeError: module 'qdarktheme' has no attribute 'enable_hi_dpi'

请问这个问题应如何得到解决

**Comment by ElluIFX** [comment]
你装的`pyqtdarktheme`包和项目的版本不符合

最简单的解决方式就是把这行删了(DP100_gui.py:54), 如果你不需要高DPI缩放的话

如果需要，安装和`requirements.txt`里**版本匹配**的`pyqtdarktheme`

**Comment by Meteor2333** [comment]
我现在使用了相同版本的pyqtdarktheme，但出现了新的报错：
Traceback (most recent call last):
  File "DP100_main.py", line 25, in <module>
  File "DP100_main.py", line 15, in main
  File "DP100_gui.py", line 24, in <module>
ModuleNotFoundError: No module named 'qdarktheme'

下面是pip list的信息
Package                Version
---------------------- -----------
cffi                   1.16.0
clr-loader             0.2.6
darkdetect             0.7.1
llvmlite               0.40.1
numba                  0.57.1
numpy                  1.24.4
pip                    24.0
pycparser              2.22
PyOpenGL               3.1.6
PyQt5                  5.15.2
PyQt5-Frameless-Window 0.2.9
PyQt5-Qt5              5.15.2
PyQt5-sip              12.8.1
PyQtDarkTheme          2.1.0
pyqtgraph              0.13.3
pythonnet              3.0.0.post1
pywin32                306
setuptools             58.1.0
simple-pid             2.0.0

**Comment by Meteor2333** [comment]
网上说这个问题是路径中带有中文目录导致的 可惜它并不适用于我

**Comment by Meteor2333** [comment]
我现在使用了相同版本的pyqtdarktheme，但出现了新的报错：
Traceback (most recent call last):
File "PyInstaller\loader\pyiboot01_bootstrap.py", line 20, in
File "PyInstaller\loader\pyimod02_importers.py", line 497, in install
File "PyInstaller\loader\pyimod02_importers.py", line 117, in init
ImportError: Cannot load frozen modules.

下面是pip list的信息
Package Version

cffi 1.16.0
clr-loader 0.2.6
darkdetect 0.7.1
llvmlite 0.40.1
numba 0.57.1
numpy 1.24.4
pip 24.0
pycparser 2.22
PyOpenGL 3.1.6
PyQt5 5.15.2
PyQt5-Frameless-Window 0.2.9
PyQt5-Qt5 5.15.2
PyQt5-sip 12.8.1
PyQtDarkTheme 2.1.0
pyqtgraph 0.13.3
pythonnet 3.0.0.post1
pywin32 306
setuptools 58.1.0
simple-pid 2.0.0

**Comment by Meteor2333** [comment]
网上说是路径有中文导致 可是我没有 但我仍然换了一个路径又出现了不同的报错：
Traceback (most recent call last):
  File "DP100_main.py", line 25, in <module>
  File "DP100_main.py", line 15, in main
  File "DP100_gui.py", line 1220, in <module>
  File "DP100_gui.py", line 199, in __init__
  File "DP100_gui.py", line 174, in set_theme
AttributeError: 'MinimizeButton' object has no attribute 'updateStyle'

**Comment by Meteor2333** [comment]
我在代码中发现了多处方法没有被定义的情况 但我不知道它是什么原因引起的

**Comment by Meteor2333** [comment]
我找到了问题所在 原因是我没有调用项目lib里的qframelesswindow
